# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Metin Uçar
email: mtn.ucar@gmail.com
description: Designer, front-end developer and overall web enthusiast
baseurl: "/"
url: "http://mtncr.com"
twitter_username: merovingian
github_username:  metinucar

# Build settings
markdown: kramdown
permalink: pretty
